export const ACTIVATE_LOADER = 'ACTIVATE_LOADER';
export const DEACTIVATE_LOADER = 'DEACTIVATE_LOADER';
export const SET_FILTERS = 'SET_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_NAVIGATION = 'SET_NAVIGATION';
export const RESET_NAVIGATION = 'RESET_NAVIGATION';
export const REPLACE_DATA = 'REPLACE_DATA';
export const APPEND_DATA = 'APPEND_DATA';
