export const FILL_BOOKS = 'FILL_BOOKS';
export const UPDATE_FILTER_SEARCH = 'UPDATE_FILTER_SEARCH';
export const RESET_FILTER = 'RESET_FILTER';
export const ACTIVATE_LOADER = 'ACTIVATE_LOADER';
export const DEACTIVATE_LOADER = 'DEACTIVATE_LOADER';
